services:
  - type: web
    name: enhanced-geospatial-frontend
    env: static
    buildCommand: "npm ci && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
