# Generated by Django 5.2.3 on 2025-07-02 17:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aois', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area of Interest',
                'verbose_name_plural': 'Areas of Interest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AOISatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersects', models.BooleanField(default=True)),
                ('intersection_area', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.aoi')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SENTINEL', 'Sentinel'), ('LANDSAT', 'Landsat'), ('MODIS', 'MODIS')], max_length=32)),
                ('tile_id', models.CharField(db_index=True, max_length=128)),
                ('sensed_at', models.DateTimeField(db_index=True)),
                ('cloud_cover', models.FloatField()),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('file_path', models.CharField(max_length=500)),
                ('bands', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aois', models.ManyToManyField(blank=True, related_name='satellite_images', through='imagery.AOISatelliteImage', to='imagery.aoi')),
            ],
            options={
                'ordering': ['-sensed_at'],
                'unique_together': {('provider', 'tile_id', 'sensed_at')},
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='imagery.aoi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='imagery.satelliteimage')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='satellite_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagery.satelliteimage'),
        ),
        migrations.CreateModel(
            name='IndexResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(max_length=32)),
                ('value', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='imagery.aoi')),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='imagery.satelliteimage')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('aoi', 'satellite_image', 'index_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aoisatelliteimage',
            unique_together={('aoi', 'satellite_image')},
        ),
    ]
