# Generated by Django 5.2.3 on 2026-01-26 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Zimbabwe', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intended_use',
            field=models.CharField(blank=True, default='', help_text='Primary intended use of the platform', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intended_use_details',
            field=models.TextField(blank=True, default='', help_text='Additional details about intended use'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_type',
            field=models.CharField(blank=True, default='', help_text='Type of organization (e.g., local_council, university, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_path',
            field=models.CharField(blank=True, default='individual', help_text='User type path: government, organization, education, individual', max_length=50),
        ),
    ]
