# Generated by Django 5.2.3 on 2025-07-02 17:18

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('download', 'Download'), ('clip', 'Clip to AOI'), ('index', 'Compute Index'), ('batch_process', 'Batch Processing'), ('custom', 'Custom Processing')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('slurm_job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('allocated_cores', models.IntegerField(blank=True, null=True)),
                ('allocated_memory_gb', models.FloatField(blank=True, null=True)),
                ('estimated_runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('log_file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_parameters', models.JSONField(default=dict)),
                ('output_files', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_aois', models.IntegerField(default=10)),
                ('max_download_size_gb', models.FloatField(default=50.0)),
                ('max_concurrent_downloads', models.IntegerField(default=3)),
                ('current_aois', models.IntegerField(default=0)),
                ('current_download_size_gb', models.FloatField(default=0.0)),
                ('current_downloads', models.IntegerField(default=0)),
                ('default_cloud_cover_threshold', models.FloatField(default=20.0)),
                ('preferred_providers', models.JSONField(blank=True, default=list)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aoisatelliteimage',
            old_name='intersection_area',
            new_name='clipped_file_size_mb',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='file_url',
            new_name='download_url',
        ),
        migrations.RenameField(
            model_name='indexresult',
            old_name='value',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='indexresult',
            old_name='file_path',
            new_name='raster_file_path',
        ),
        migrations.RemoveField(
            model_name='download',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='download',
            name='satellite_image',
        ),
        migrations.AddField(
            model_name='aoi',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoi',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aoi',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aoi',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aoi',
            name='upload_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aoi',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='clipped_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='clipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='coverage_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='intersection_area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoisatelliteimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='download',
            name='clip_to_aoi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='download',
            name='compression',
            field=models.CharField(choices=[('none', 'None'), ('lzw', 'LZW'), ('jpeg', 'JPEG'), ('deflate', 'Deflate')], default='lzw', max_length=20),
        ),
        migrations.AddField(
            model_name='download',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='file_size_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='download',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='download',
            name='output_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='download',
            name='output_format',
            field=models.CharField(choices=[('geotiff', 'GeoTIFF'), ('cog', 'Cloud Optimized GeoTIFF'), ('netcdf', 'NetCDF')], default='geotiff', max_length=20),
        ),
        migrations.AddField(
            model_name='download',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='download',
            name='satellite_images',
            field=models.ManyToManyField(related_name='downloads', to='imagery.satelliteimage'),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='computation_method',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='custom_formula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='histogram_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='mean_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='median_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='std_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='archive_status',
            field=models.CharField(choices=[('online', 'Online'), ('nearline', 'Nearline'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='coordinate_system',
            field=models.CharField(default='EPSG:4326', max_length=20),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='data_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='file_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='ingested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='pixel_resolution_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='processing_level',
            field=models.CharField(default='L1C', max_length=10),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='scene_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='indexresult',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('NDWI', 'Normalized Difference Water Index'), ('EVI', 'Enhanced Vegetation Index'), ('SAVI', 'Soil Adjusted Vegetation Index'), ('NDBI', 'Normalized Difference Built-up Index'), ('MNDWI', 'Modified Normalized Difference Water Index'), ('CUSTOM', 'Custom Index')], max_length=32),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='cloud_cover',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='satelliteimage',
            name='provider',
            field=models.CharField(choices=[('SENTINEL1', 'Sentinel-1 (SAR)'), ('SENTINEL2', 'Sentinel-2 (Optical)'), ('LANDSAT8', 'Landsat 8'), ('LANDSAT9', 'Landsat 9'), ('MODIS', 'MODIS'), ('PLANET', 'Planet'), ('CUSTOM', 'Custom Provider')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['user', '-created_at'], name='imagery_aoi_user_id_be96d8_idx'),
        ),
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['is_public', '-created_at'], name='imagery_aoi_is_publ_8bca60_idx'),
        ),
        migrations.AddIndex(
            model_name='aoisatelliteimage',
            index=models.Index(fields=['aoi', '-created_at'], name='imagery_aoi_aoi_id_1e21ee_idx'),
        ),
        migrations.AddIndex(
            model_name='aoisatelliteimage',
            index=models.Index(fields=['satellite_image', '-created_at'], name='imagery_aoi_satelli_49eda7_idx'),
        ),
        migrations.AddIndex(
            model_name='aoisatelliteimage',
            index=models.Index(fields=['clipping_status'], name='imagery_aoi_clippin_f95189_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['provider', '-sensed_at'], name='imagery_sat_provide_42eac2_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['cloud_cover', '-sensed_at'], name='imagery_sat_cloud_c_81cd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['is_available', '-sensed_at'], name='imagery_sat_is_avai_d0a5b5_idx'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='download',
            name='processing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagery.processingjob'),
        ),
        migrations.AddField(
            model_name='indexresult',
            name='processing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagery.processingjob'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['user', 'status'], name='imagery_dow_user_id_d7defb_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['status', '-requested_at'], name='imagery_dow_status_6468bd_idx'),
        ),
        migrations.AddIndex(
            model_name='indexresult',
            index=models.Index(fields=['aoi', 'index_type', '-computed_at'], name='imagery_ind_aoi_id_e6e96e_idx'),
        ),
        migrations.AddIndex(
            model_name='indexresult',
            index=models.Index(fields=['satellite_image', 'index_type'], name='imagery_ind_satelli_c4a72e_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['user', 'status'], name='imagery_pro_user_id_fb1b99_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'priority'], name='imagery_pro_status_67002b_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['job_type', '-submitted_at'], name='imagery_pro_job_typ_007799_idx'),
        ),
    ]
