# Generated by Django 5.2.3 on 2026-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0003_add_userprofile_columns_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of modules user can access (e.g., dashboard, imagery, data_store). Staff can upload/manage files, regular users download only.'),
        ),
    ]
