# Generated by Django 5.2.3 on 2025-07-03 08:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0003_alter_aoi_user_alter_download_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBoundarySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the boundary set (e.g., 'Zimbabwe Administrative Boundaries 2023')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the boundary set')),
                ('source', models.CharField(blank=True, help_text='Data source or provider', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('coordinate_system', models.CharField(default='EPSG:4326', max_length=50)),
                ('data_year', models.IntegerField(blank=True, help_text='Year the boundaries represent', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Available to all users')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('total_boundaries', models.IntegerField(default=0)),
                ('levels_included', models.JSONField(default=list, help_text='List of admin levels included')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boundary_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Boundary Set',
                'verbose_name_plural': 'Administrative Boundary Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('country', 'Country'), ('province', 'Province/State'), ('district', 'District/County'), ('ward', 'Ward/Municipality')], max_length=20)),
                ('name', models.CharField(help_text='Official name of the administrative unit', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Official code (if available)', max_length=50)),
                ('name_0', models.CharField(blank=True, help_text='Country name', max_length=255)),
                ('name_1', models.CharField(blank=True, help_text='Province/State name', max_length=255)),
                ('name_2', models.CharField(blank=True, help_text='District/County name', max_length=255)),
                ('name_3', models.CharField(blank=True, help_text='Ward/Municipality name', max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('perimeter_km', models.FloatField(blank=True, null=True)),
                ('attributes', models.JSONField(default=dict, help_text='Additional attributes from source data')),
                ('is_active', models.BooleanField(default=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='imagery.administrativeboundary')),
                ('boundary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='imagery.administrativeboundaryset')),
            ],
            options={
                'verbose_name': 'Administrative Boundary',
                'verbose_name_plural': 'Administrative Boundaries',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['boundary_set', 'level'], name='imagery_adm_boundar_b0e1f4_idx'), models.Index(fields=['level', 'name'], name='imagery_adm_level_46877e_idx'), models.Index(fields=['name_0', 'name_1', 'name_2'], name='imagery_adm_name_0_f8a832_idx')],
                'unique_together': {('boundary_set', 'level', 'name', 'name_0', 'name_1', 'name_2')},
            },
        ),
    ]
