# Generated by Django 5.2.3 on 2026-06-08 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0007_store_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('search', 'Search'), ('download', 'Download'), ('upload', 'Upload'), ('analysis', 'Analysis Run'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart'), ('checkout', 'Checkout'), ('purchase', 'Purchase'), ('review', 'Review Submitted'), ('login', 'Login'), ('signup', 'Signup'), ('error', 'Error Occurred')], max_length=30)),
                ('event_category', models.CharField(blank=True, max_length=50)),
                ('event_label', models.CharField(blank=True, max_length=255)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('page_load_time', models.FloatField(blank=True, help_text='in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('revenue', 'Revenue'), ('users', 'User Count'), ('orders', 'Order Count'), ('downloads', 'Download Count'), ('active_users', 'Active Users'), ('conversion_rate', 'Conversion Rate'), ('avg_order_value', 'Average Order Value'), ('customer_lifetime_value', 'Customer Lifetime Value'), ('churn_rate', 'Churn Rate'), ('data_processed', 'Data Processed (GB)'), ('api_calls', 'API Calls'), ('storage_used', 'Storage Used (GB)'), ('custom', 'Custom Metric')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('segment', models.CharField(blank=True, help_text='e.g., user_type, region, product_category', max_length=100)),
                ('segment_value', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Metric',
                'verbose_name_plural': 'Business Metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout and widget positions')),
                ('widgets', models.JSONField(default=list, help_text='List of widgets and their configurations')),
                ('refresh_interval', models.IntegerField(default=60, help_text='Auto-refresh interval in seconds')),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(max_length=50)),
                ('target_metric', models.CharField(max_length=100)),
                ('forecast_data', models.JSONField(default=list, help_text='Time series forecast data')),
                ('forecast_start', models.DateTimeField()),
                ('forecast_end', models.DateTimeField()),
                ('confidence_level', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('upper_bound', models.JSONField(default=list)),
                ('lower_bound', models.JSONField(default=list)),
                ('actual_data', models.JSONField(blank=True, default=list)),
                ('mean_absolute_error', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeospatialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('coverage', 'Coverage Analysis'), ('hotspot', 'Hotspot Analysis'), ('temporal', 'Temporal Analysis'), ('change_detection', 'Change Detection'), ('density', 'Density Analysis'), ('proximity', 'Proximity Analysis'), ('clustering', 'Spatial Clustering'), ('prediction', 'Predictive Modeling')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('bounds', models.JSONField(default=dict, help_text='Geographic bounding box')),
                ('results', models.JSONField(default=dict)),
                ('visualization_url', models.CharField(blank=True, max_length=500)),
                ('statistics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Geospatial Analytics',
                'verbose_name_plural': 'Geospatial Analytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Trend Identified'), ('anomaly', 'Anomaly Detected'), ('opportunity', 'Business Opportunity'), ('recommendation', 'Recommendation'), ('prediction', 'Prediction'), ('alert', 'Alert'), ('optimization', 'Optimization Suggestion')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=list)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_actions', models.JSONField(default=list)),
                ('potential_impact', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('demand_forecast', 'Demand Forecasting'), ('churn_prediction', 'Churn Prediction'), ('revenue_forecast', 'Revenue Forecasting'), ('usage_prediction', 'Usage Prediction'), ('anomaly_detection', 'Anomaly Detection'), ('recommendation', 'Recommendation Engine')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('training_data_start', models.DateTimeField()),
                ('training_data_end', models.DateTimeField()),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predictive Model',
                'verbose_name_plural': 'Predictive Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('user_activity', 'User Activity Report'), ('product_performance', 'Product Performance'), ('geographic', 'Geographic Analysis'), ('revenue', 'Revenue Report'), ('usage', 'Platform Usage'), ('inventory', 'Inventory Report'), ('customer', 'Customer Analytics'), ('custom', 'Custom Report')], max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters like date range, filters, etc.')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='generating', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='Report results and data')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, help_text='e.g., daily, weekly, monthly', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=50)),
                ('pattern_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('frequency', models.CharField(help_text='e.g., daily, weekly, occasional', max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pattern_data', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('occurrences', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Behavior Pattern',
                'verbose_name_plural': 'User Behavior Patterns',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_product_user_order_review',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_product_wishlist',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='imagery_ord_user_id_fcb150_idx',
            old_name='imagery_ord_user_id_idx1',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='imagery_ord_status_78dda8_idx',
            old_name='imagery_ord_status_idx2',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='imagery_ord_order_n_d86ce7_idx',
            old_name='imagery_ord_order_n_idx3',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='imagery_pro_product_62697b_idx',
            old_name='imagery_pro_product_idx1',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='imagery_pro_categor_277cce_idx',
            old_name='imagery_pro_categor_idx2',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='imagery_pro_created_7b9d9b_idx',
            old_name='imagery_pro_created_idx3',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='imagery_pro_rating__f849a8_idx',
            old_name='imagery_pro_rating__idx4',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='imagery_pro_product_d34714_idx',
            old_name='imagery_pro_product_idx5',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='imagery_pro_product_4cca84_idx',
            old_name='imagery_pro_product_idx6',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['metric_type', '-period_start'], name='imagery_bus_metric__2862bc_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['period_type', '-period_start'], name='imagery_bus_period__61ed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['segment', 'segment_value', '-period_start'], name='imagery_bus_segment_4f51e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmetric',
            unique_together={('metric_type', 'period_type', 'period_start', 'segment', 'segment_value')},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geospatialanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geospatial_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insight',
            name='relevant_for_users',
            field=models.ManyToManyField(blank=True, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecast',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='imagery.predictivemodel'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbehaviorpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', '-created_at'], name='imagery_ana_user_id_25b67b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', '-created_at'], name='imagery_ana_event_t_1b26e8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', '-created_at'], name='imagery_ana_session_fafcdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='geospatialanalytics',
            index=models.Index(fields=['user', '-created_at'], name='imagery_geo_user_id_0de4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='geospatialanalytics',
            index=models.Index(fields=['analysis_type', '-created_at'], name='imagery_geo_analysi_0762bc_idx'),
        ),
        migrations.AddIndex(
            model_name='geospatialanalytics',
            index=models.Index(fields=['status', '-created_at'], name='imagery_geo_status_b93f08_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['insight_type', '-created_at'], name='imagery_ins_insight_a44ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['priority', '-created_at'], name='imagery_ins_priorit_8f6c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['is_active', '-created_at'], name='imagery_ins_is_acti_a4629d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', '-created_at'], name='imagery_rep_created_bba1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', '-created_at'], name='imagery_rep_report__c54a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='imagery_rep_status_29979d_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorpattern',
            index=models.Index(fields=['user', '-last_seen'], name='imagery_use_user_id_9b248e_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehaviorpattern',
            index=models.Index(fields=['pattern_type', '-last_seen'], name='imagery_use_pattern_db87da_idx'),
        ),
    ]
